# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-06 06:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_que',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
