# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-06 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0002_question_date_que'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='que',
            field=models.TextField(blank=True, null=True),
        ),
    ]
