# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-06 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0004_auto_20180706_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='id',
            new_name='que_id',
        ),
    ]
