# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-06 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0006_auto_20180706_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('date_que',), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
