# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-06 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0007_auto_20180706_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='author_que',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='que_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('1', 'C++'), ('2', 'Python'), ('3', 'Django'), ('4', 'Java')], max_length=100),
        ),
    ]
