# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-06 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0008_auto_20180706_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('1', 'C++'), ('2', 'Python'), ('3', 'Django'), ('4', 'Java'), ('5', 'Shell'), ('6', 'C')], max_length=100),
        ),
    ]
