# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-06 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0009_auto_20180706_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='que_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
