# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-06 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0011_auto_20180706_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('1', 'C++'), ('2', 'Python'), ('3', 'Django'), ('4', 'Java'), ('5', 'Shell'), ('6', 'C'), ('7', 'Panda'), ('8', 'TensorFlow')], max_length=100),
        ),
    ]
